[package]
name = "resurgence"
version = "0.1.1"
edition = "2021"
description = "A VM backend library that makes developing interpreters easy. Can be used either as an entire backend, or to create a backend"
license = "GPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smartstring = {version = "1.0.1", features = ["proptest", "serde"]}