[package]
name = "resurgence"
version = "0.1.6"
edition = "2021"
description = "A VM backend designed to be embedded in an application"
license = "MIT"
authors = ["Mahid Sheikh <sheikhmahid1@hotmail.com>"]
readme = "README.md"
homepage = "https://github.com/StandingPadAnimations/Resurgence"
repository = "https://github.com/StandingPadAnimations/Resurgence"

[dependencies]
byteorder = "1.4.3"

[lib]
doctest = false
