[package]
name = "resurgence"
version = "0.1.5"
edition = "2021"
description = "A VM backend library that makes developing interpreters easy. Can be used either as an entire backend, or to create a backend"
license = "MIT"
authors = ["Mahid Sheikh <sheikhmahid1@hotmail.com>"]
readme = "README.md"
homepage = "https://github.com/StandingPadAnimations/Resurgence"
repository = "https://github.com/StandingPadAnimations/Resurgence"

[dependencies]
smartstring = {version = "1.0.1", features = ["proptest", "serde"]}

[lib]
doctest = false